[package]
name = "gdax_websocket_client"
version = "0.1.0"
authors = ["paul.webster"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
websocket = "0.26.2"